# Wrangler configuration for Cloudflare Pages
# This file is required for Cloudflare Pages deployment

name = "penstip-frontend"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run build:production"
cwd = "."

[build.upload]
format = "directory"
dir = "dist"

# Environment variables
[vars]
NODE_ENV = "production"

# Build environment
[env.production]
name = "penstip-frontend-production"

[env.preview]
name = "penstip-frontend-preview" 